import React, { useEffect, useState } from 'react';
import { Bell, CheckCircle2, Clock, Info, AlertTriangle } from 'lucide-react';
import { notificationApi } from '@/services/notificationApi';
import type { NotificationItem } from '@/types/notification.types';
import { Button } from '@/components/ui/button';
export const InstructorNotifications: React.FC = () => { const [items, setItems] = useState<NotificationItem[]>([]); const [loading, setLoading] = useState(true); const [readFilter, setReadFilter] = useState<'all' | 'unread'>('all'); const load = async () => { setLoading(true); try {
    const data = await notificationApi.list({ limit: 50, ...(readFilter === 'unread' ? { read: false } : {}) });
    setItems(data.items);
}
finally {
    setLoading(false);
} }; useEffect(() => { void load(); }, [readFilter]); const markRead = async (id: string) => { await notificationApi.markRead(id); setItems(v => v.map(n => n._id === id ? { ...n, readAt: new Date().toISOString() } : n)); }; const markAll = async () => { await notificationApi.markAllRead(); setItems(v => v.map(n => ({ ...n, readAt: n.readAt || new Date().toISOString() }))); }; const unread = items.filter(n => !n.readAt).length; return <div className="space-y-6"><div className="flex items-start justify-between"><div><h1 className="text-3xl font-extrabold">Thông báo</h1><p className="text-muted-foreground mt-1">Thông báo và cập nhật từ SecureLearn.</p></div>{unread > 0 && <Button variant="outline" onClick={markAll}><CheckCircle2 className="w-4 h-4 mr-2"/>Đánh dấu tất cả đã đọc</Button>}</div><div className="flex gap-2"><Button variant={readFilter === 'all' ? 'default' : 'outline'} onClick={() => setReadFilter('all')}>Tất cả</Button><Button variant={readFilter === 'unread' ? 'default' : 'outline'} onClick={() => setReadFilter('unread')}>Chưa đọc ({unread})</Button></div>{loading ? <p className="text-zinc-500">Đang tải...</p> : items.length === 0 ? <div className="text-center py-16 text-zinc-400"><Bell className="w-12 h-12 mx-auto mb-3 opacity-20"/><p>Không có thông báo nào.</p></div> : <div className="space-y-3">{items.map(n => <article key={n._id} onClick={() => { if (!n.readAt)
    void markRead(n._id); }} className={`relative bg-white dark:bg-zinc-900 border rounded-2xl p-5 cursor-pointer ${!n.readAt ? 'border-primary/40 shadow-sm' : 'border-zinc-200 dark:border-zinc-800'}`}><div className="flex gap-4"><div className="w-10 h-10 rounded-xl bg-primary/10 text-primary flex items-center justify-center">{n.type.includes('FAILED') || n.type === 'COURSE_REJECTED' ? <AlertTriangle className="w-4 h-4"/> : <Info className="w-4 h-4"/>}</div><div><span className="text-xs text-zinc-400 flex items-center gap-1"><Clock className="w-3 h-3"/>{new Date(n.createdAt).toLocaleString('vi-VN')}</span><h3 className="font-bold mt-1">{n.title}</h3><p className="text-sm text-zinc-500 mt-1">{n.body}</p></div></div>{!n.readAt && <span className="absolute top-4 right-4 w-2.5 h-2.5 rounded-full bg-primary"/>}</article>)}</div>}</div>; };

